# Generated by Django 3.1.7 on 2021-04-16 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0017_auto_20210416_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('product', models.CharField(blank=True, max_length=500, null=True)),
                ('customer', models.CharField(blank=True, max_length=500, null=True)),
                ('customer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.customer')),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_task_product', to='shop.product')),
            ],
            options={
                'verbose_name': 'SaleTask',
                'verbose_name_plural': 'SaleTasks',
            },
        ),
        migrations.CreateModel(
            name='SaleProductRelated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_product_id', models.IntegerField(blank=True, null=True)),
                ('qty_index', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('calculation_type', models.CharField(blank=True, max_length=250, null=True)),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_related_product', to='shop.product')),
            ],
            options={
                'verbose_name': 'SaleProductRelated',
                'verbose_name_plural': 'SaleProductRelateds',
            },
        ),
        migrations.CreateModel(
            name='SaleHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('customer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.customer')),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_history_product', to='shop.product')),
            ],
            options={
                'verbose_name': 'SaleHistory',
                'verbose_name_plural': 'SaleHistories',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('date', models.CharField(blank=True, max_length=500, null=True)),
                ('product', models.CharField(blank=True, max_length=500, null=True)),
                ('customer', models.CharField(blank=True, max_length=500, null=True)),
                ('customer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.customer')),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_product', to='shop.product')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
            },
        ),
    ]
