# Generated by Django 3.1.3 on 2020-11-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogcategory',
            name='comment_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='catalogcategory',
            name='comment_ru',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='catalogcategory',
            name='comment_uk',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='catalogcategory',
            name='name_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='catalogcategory',
            name='name_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='catalogcategory',
            name='name_uk',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='comment_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='comment_ru',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='comment_uk',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uk',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='full_text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='full_text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='full_text_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='intro_text_en',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='intro_text_ru',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='intro_text_uk',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='meta_tag_description_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='meta_tag_description_ru',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='meta_tag_description_uk',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='meta_tag_keyword_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='meta_tag_keyword_ru',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='meta_tag_keyword_uk',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='meta_tag_title_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='meta_tag_title_ru',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='meta_tag_title_uk',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='title_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='title_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='title_uk',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='deliverymethod',
            name='comment_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverymethod',
            name='comment_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverymethod',
            name='comment_uk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverymethod',
            name='name_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='deliverymethod',
            name='name_ru',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='deliverymethod',
            name='name_uk',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='deliverymethod',
            name='red_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverymethod',
            name='red_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverymethod',
            name='red_uk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='comment_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='comment_ru',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='comment_uk',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='name_en',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='name_ru',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='name_uk',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='keywords_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='keywords_ru',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='keywords_uk',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(default='Product', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(default='Product', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_uk',
            field=models.CharField(default='Product', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='runstring',
            name='comment_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='runstring',
            name='comment_ru',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='runstring',
            name='comment_uk',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='runstring',
            name='full_text_en',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='runstring',
            name='full_text_ru',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='runstring',
            name='full_text_uk',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='userrequesttype',
            name='comment_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userrequesttype',
            name='comment_ru',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userrequesttype',
            name='comment_uk',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userrequesttype',
            name='name_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='userrequesttype',
            name='name_ru',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='userrequesttype',
            name='name_uk',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
