# Generated by Django 3.1.7 on 2021-03-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='supplier_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='is_active',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='enabled',
            field=models.BooleanField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='gallery_attribute',
            field=models.CharField(blank=True, default='article', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='is_recommended',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='kind',
            field=models.CharField(blank=True, default='secondary', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='sort_index',
            field=models.IntegerField(blank=True, default=999, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='wait_list',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
    ]
