# Generated by Django 3.1.7 on 2021-03-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210303_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogcategory',
            name='url',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
