# Generated by Django 3.1.7 on 2021-03-17 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_catalogcategory_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogcategory',
            name='url',
        ),
    ]
