# Generated by Django 3.1.6 on 2021-02-15 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210215_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='main_customer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.customer'),
        ),
    ]
