# Generated by Django 3.1.6 on 2021-02-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210215_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='main_customer',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='manager',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
