# Generated by Django 3.1.7 on 2021-03-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_catalogcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True),
        ),
    ]
