# Generated by Django 3.1.6 on 2021-02-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210215_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='region_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
