# Generated by Django 3.1.6 on 2021-02-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20210215_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='enabled',
            field=models.BooleanField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='gallery_attribute',
            field=models.CharField(default='article', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='is_recommended',
            field=models.BooleanField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='kind',
            field=models.CharField(default='secondary', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='sort_index',
            field=models.IntegerField(default=999, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='source_type',
            field=models.CharField(default='1C', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='wait_list',
            field=models.BooleanField(default=0, null=True),
        ),
    ]
