# Generated by Django 3.1.7 on 2021-03-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20210320_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product/category_image/'),
        ),
    ]
