# Generated by Django 3.1.6 on 2021-02-15 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20210215_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricetype',
            name='access_policy_data',
        ),
        migrations.RemoveField(
            model_name='pricetype',
            name='enabled',
        ),
        migrations.RemoveField(
            model_name='pricetype',
            name='sort_index',
        ),
    ]
