# Generated by Django 3.1.7 on 2021-03-23 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_catalogcategory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='account',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartProduct',
        ),
    ]
