# Generated by Django 3.1.7 on 2021-03-23 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20210323_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sort_price',
            new_name='price',
        ),
    ]
