# Generated by Django 3.1.6 on 2021-02-15 13:32

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20210215_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogcategory',
            name='parent',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='catalogcategory',
            name='enabled',
            field=models.BooleanField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='catalogcategory',
            name='parent_id',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='shop.catalogcategory'),
        ),
        migrations.AlterField(
            model_name='catalogcategory',
            name='sort_index',
            field=models.IntegerField(default=999, null=True),
        ),
    ]
