# Generated by Django 3.1.7 on 2021-03-24 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20210323_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dropshippingwallettransfer',
            name='agreement_id',
        ),
        migrations.RemoveField(
            model_name='dropshippingwallettransfer',
            name='currency_id',
        ),
        migrations.RemoveField(
            model_name='dropshippingwallettransfer',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='agreement_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_city_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_point_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_service_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='point_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='currency_id',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='orderpayment',
            name='currency_id',
        ),
        migrations.RemoveField(
            model_name='orderpayment',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='ordersourcestatistic',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='ordersourcestatistic',
            name='product_id',
        ),
        migrations.DeleteModel(
            name='DropshippingWallet',
        ),
        migrations.DeleteModel(
            name='DropshippingWalletTransfer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='OrderPayment',
        ),
        migrations.DeleteModel(
            name='OrderSourceStatistic',
        ),
    ]
