# Generated by Django 3.1.6 on 2021-02-15 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20210215_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogcategory',
            name='level',
        ),
        migrations.RemoveField(
            model_name='catalogcategory',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='catalogcategory',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='catalogcategory',
            name='tree_id',
        ),
    ]
