# Generated by Django 3.1.7 on 2021-03-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20210324_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufacturer_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='model_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
