# Generated by Django 3.1.6 on 2021-02-15 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20210215_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='group',
            new_name='group_name',
        ),
    ]
