# Generated by Django 3.1.7 on 2021-04-01 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20210326_1112'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WaitList',
        ),
    ]
