# Generated by Django 3.1.6 on 2021-02-15 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20210215_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='offer',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.pricecategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='delete_flag',
            field=models.BooleanField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_exists',
            field=models.BooleanField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_category',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
