# Generated by Django 3.1.6 on 2021-02-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20210215_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='comment_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='comment_ru',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='comment_uk',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
