# Generated by Django 3.1.6 on 2021-02-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20210215_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ABC',
        ),
        migrations.AddField(
            model_name='product',
            name='abc',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
