# Generated by Django 3.1.7 on 2021-04-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20210416_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_recommended',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
    ]
