# Generated by Django 3.1.7 on 2021-05-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_offer_is_recommended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='email',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='phone',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
