# Generated by Django 3.1.6 on 2021-02-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20210215_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pack_qty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sort_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='source_type',
            field=models.CharField(default='1C', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
    ]
