# Generated by Django 3.1.6 on 2021-02-15 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20210215_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpoint',
            name='customer',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='customerpoint',
            name='customer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_customer', to='shop.customer'),
        ),
    ]
