# Generated by Django 3.1.6 on 2021-02-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20210216_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdiscount',
            name='criteria_id',
        ),
        migrations.AddField(
            model_name='customerdiscount',
            name='agreement',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='customerdiscount',
            name='customer',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='customerdiscount',
            name='price_type',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='customerdiscount',
            name='source_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerdiscount',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True),
        ),
    ]
