# Generated by Django 3.2.5 on 2021-07-19 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_alter_product_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='parent_category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_parent_category_id', to='shop.catalogcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_brand_id', to='shop.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_category_id', to='shop.catalogcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='offer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_offer_id', to='shop.offer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_price_category_id', to='shop.pricecategory'),
        ),
    ]
