# Generated by Django 3.1.6 on 2021-02-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_auto_20210216_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdiscount',
            name='source_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
