# Generated by Django 3.2.5 on 2021-07-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_auto_20210719_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='name',
            field=models.CharField(blank=True, default='ProductImage', max_length=250, null=True),
        ),
    ]
