# Generated by Django 3.1.6 on 2021-02-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_auto_20210216_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdiscount',
            name='brand',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
