# Generated by Django 3.2.5 on 2021-07-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_productimage_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='source_customer',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='source_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
