# Generated by Django 3.2.5 on 2021-07-28 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_auto_20210726_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='source_customer',
        ),
    ]
