# Generated by Django 3.1.6 on 2021-02-16 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_auto_20210216_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dropshippingwallet',
            old_name='order',
            new_name='order_order',
        ),
    ]
