# Generated by Django 3.2.8 on 2021-10-08 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_remove_manager_source_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturerBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('source_id', models.CharField(blank=True, max_length=300, null=True)),
                ('manufacturerId', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'ManufacturerBrand',
                'verbose_name_plural': 'ManufacturerBrands',
            },
        ),
        migrations.AddField(
            model_name='brand',
            name='manufacturer_brand_source',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='manufacturer_brand',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.manufacturerbrand'),
        ),
    ]
