# Generated by Django 3.2.8 on 2021-10-08 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_auto_20211008_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufacturerbrand',
            old_name='manufacturerId',
            new_name='manufacturer_id',
        ),
    ]
