# Generated by Django 3.1.6 on 2021-02-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_auto_20210216_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='deficitreserve',
            name='product',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='product',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='deficitreserve',
            name='amount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='amount_account',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='amount_total',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
