# Generated by Django 3.1.6 on 2021-02-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_auto_20210216_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='cross',
            name='product',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='productapplicability',
            name='product',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='productdescription',
            name='product',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
