# Generated by Django 3.1.6 on 2021-02-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_auto_20210216_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='cross',
            name='brand',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
