# Generated by Django 3.1.6 on 2021-02-16 13:38

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_cross_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='source',
        ),
        migrations.RemoveField(
            model_name='order',
            name='update_date',
        ),
        migrations.AddField(
            model_name='order',
            name='agreement',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='has_precept',
            field=models.BooleanField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='has_waybill',
            field=models.BooleanField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_source',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='complete',
            field=models.BooleanField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='declared_currency',
            field=models.BooleanField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_contact_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_contact_surname',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_is_invoice_off',
            field=models.BooleanField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_pay_on_delivery',
            field=models.BooleanField(default=0, null=True),
        ),
    ]
