# Generated by Django 3.1.6 on 2021-02-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_auto_20210216_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogcategory',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='catalogcategory',
            name='name_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='catalogcategory',
            name='name_ru',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='catalogcategory',
            name='name_uk',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
