# Generated by Django 3.1.6 on 2021-02-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_auto_20210217_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogcategory',
            name='name',
            field=models.CharField(default='Catalog', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='catalogcategory',
            name='name_en',
            field=models.CharField(default='Catalog', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='catalogcategory',
            name='name_ru',
            field=models.CharField(default='Catalog', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='catalogcategory',
            name='name_uk',
            field=models.CharField(default='Catalog', max_length=500, null=True),
        ),
    ]
