# Generated by Django 3.1.6 on 2021-02-17 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_auto_20210217_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogcategory',
            name='level',
        ),
        migrations.RemoveField(
            model_name='catalogcategory',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='catalogcategory',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='catalogcategory',
            name='tree_id',
        ),
    ]
