# Generated by Django 3.1.7 on 2021-03-24 09:55

import creditcards.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0013_auto_20210324_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField(blank=True, default=0, null=True)),
                ('order_date', models.CharField(blank=True, max_length=300, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('delivery_contact', models.CharField(blank=True, max_length=250, null=True)),
                ('delivery_contact_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('order_number', models.CharField(blank=True, max_length=250, null=True)),
                ('waybill_number', models.CharField(blank=True, max_length=250, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=250, null=True)),
                ('order_source', models.CharField(blank=True, max_length=300, null=True)),
                ('is_pay_on_delivery', models.BooleanField(default=0, null=True)),
                ('pay_on_delivery_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('import_reason', models.TextField(blank=True, null=True)),
                ('import_status', models.CharField(blank=True, max_length=250, null=True)),
                ('partner_code', models.CharField(blank=True, max_length=250, null=True)),
                ('declared_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('declared_currency', models.BooleanField(default=1, null=True)),
                ('source_type', models.CharField(default='B2B', max_length=250, null=True)),
                ('delivery_contact_surname', models.CharField(blank=True, max_length=250, null=True)),
                ('declaration_number', models.CharField(blank=True, max_length=250, null=True)),
                ('delivery_contact_middlename', models.CharField(blank=True, max_length=250, null=True)),
                ('delivery_is_invoice_off', models.BooleanField(blank=True, default=1, null=True)),
                ('agreement', models.CharField(blank=True, max_length=300, null=True)),
                ('has_precept', models.BooleanField(blank=True, default=0, null=True)),
                ('has_waybill', models.BooleanField(blank=True, default=0, null=True)),
                ('paid', models.BooleanField(blank=True, default=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('agreement_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_agreement', to='shop.customeragreement')),
                ('delivery_city_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_del_city', to='shop.deliverycity')),
                ('delivery_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_delivery', to='shop.deliverymethod')),
                ('delivery_point_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_del_point', to='shop.deliverypoint')),
                ('delivery_service_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_del_point', to='shop.deliveryservice')),
                ('point_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_customer_point', to='shop.customerpoint')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.customer')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='OrderSourceStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(blank=True, max_length=250, null=True)),
                ('add_date', models.DateTimeField(default=datetime.datetime.today, null=True)),
                ('customer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_statistic_customer', to='shop.customer')),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_statistic_product', to='shop.product')),
            ],
            options={
                'verbose_name': 'OrderSourceStatistic',
                'verbose_name_plural': 'OrderSourceStatistics',
            },
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('date_payment', models.DateTimeField(default=datetime.datetime.today, null=True)),
                ('payment_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('data', models.TextField(blank=True, null=True)),
                ('receiver_commission', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('sender_commission', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('currency_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_payment_currency', to='shop.currency')),
                ('order_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_payment_order', to='orders.order')),
            ],
            options={
                'verbose_name': 'OrderPayment',
                'verbose_name_plural': 'OrderPayments',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True)),
                ('order_source', models.CharField(blank=True, max_length=300, null=True)),
                ('reserved', models.IntegerField(default=0, null=True)),
                ('executed', models.IntegerField(default=0, null=True)),
                ('old_qty', models.IntegerField(blank=True, null=True)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('purchase_qty', models.IntegerField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('purchase_currency_id', models.IntegerField(blank=True, null=True)),
                ('purchase_order_id', models.IntegerField(blank=True, null=True)),
                ('purchase_item_id', models.IntegerField(blank=True, null=True)),
                ('partner_branch', models.CharField(blank=True, max_length=250, null=True)),
                ('product_source', models.CharField(blank=True, max_length=300, null=True)),
                ('currency_source', models.CharField(blank=True, max_length=300, null=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_item_currency', to='shop.currency')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_item_order', to='orders.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_item_product', to='shop.product')),
            ],
            options={
                'verbose_name': 'OrderItem',
                'verbose_name_plural': 'OrderItems',
            },
        ),
        migrations.CreateModel(
            name='DropshippingWalletTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('date', models.DateTimeField(default=datetime.datetime.today, null=True)),
                ('card', creditcards.models.CardNumberField(blank=True, max_length=25, null=True)),
                ('agreement_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_transfer_agreement', to='shop.customeragreement')),
                ('currency_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_transfer_currency', to='shop.currency')),
                ('order_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_transfer_order', to='orders.order')),
            ],
            options={
                'verbose_name': 'DropshippingWalletTransfer',
                'verbose_name_plural': 'DropshippingWalletTransfers',
            },
        ),
        migrations.CreateModel(
            name='DropshippingWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True)),
                ('order_order', models.CharField(blank=True, max_length=300, null=True)),
                ('agreement', models.CharField(blank=True, max_length=300, null=True)),
                ('agreement_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_wallet_agreement', to='shop.customeragreement')),
                ('currency_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_wallet_currency', to='shop.currency')),
                ('order_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d_wallet_order', to='orders.order')),
            ],
            options={
                'verbose_name': 'DropshippingWallet',
                'verbose_name_plural': 'DropshippingWallets',
            },
        ),
    ]
