# Generated by Django 3.1.7 on 2021-04-16 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('shipping', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dropshippingwallettransfer',
            name='agreement_id',
        ),
        migrations.RemoveField(
            model_name='dropshippingwallettransfer',
            name='currency_id',
        ),
        migrations.RemoveField(
            model_name='dropshippingwallettransfer',
            name='order_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='agreement_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_agreement', to='customers.customeragreement'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_city_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_del_city', to='shipping.deliverycity'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_delivery', to='shipping.deliverymethod'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_point_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_del_point', to='shipping.deliverypoint'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_service_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_del_point', to='shipping.deliveryservice'),
        ),
        migrations.AlterField(
            model_name='order',
            name='point_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_customer_point', to='customers.customerpoint'),
        ),
        migrations.DeleteModel(
            name='DropshippingWallet',
        ),
        migrations.DeleteModel(
            name='DropshippingWalletTransfer',
        ),
    ]
