# Generated by Django 3.1.7 on 2021-04-20 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210416_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='declaration_number_status',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='partner_branch',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
