# Generated by Django 3.1.7 on 2021-04-16 11:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, max_length=250, null=True)),
                ('ref', models.CharField(blank=True, max_length=250, null=True)),
                ('name', models.CharField(max_length=250)),
                ('create_date', models.DateTimeField(default=datetime.datetime.today, null=True)),
                ('update_date', models.DateTimeField(default=datetime.datetime.today, null=True)),
            ],
            options={
                'verbose_name': 'DeliveryCity',
                'verbose_name_plural': 'DeliveryCities',
            },
        ),
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=250, null=True)),
                ('region_available', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=250)),
                ('name_ru', models.CharField(max_length=250, null=True)),
                ('name_uk', models.CharField(max_length=250, null=True)),
                ('name_en', models.CharField(max_length=250, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('comment_ru', models.TextField(blank=True, null=True)),
                ('comment_uk', models.TextField(blank=True, null=True)),
                ('comment_en', models.TextField(blank=True, null=True)),
                ('red', models.TextField(blank=True, null=True)),
                ('red_ru', models.TextField(blank=True, null=True)),
                ('red_uk', models.TextField(blank=True, null=True)),
                ('red_en', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'DeliveryMethod',
                'verbose_name_plural': 'DeliveryMethods',
            },
        ),
        migrations.CreateModel(
            name='DeliveryService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('has_to_door', models.BooleanField(default=0)),
                ('parameters', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'DeliveryService',
                'verbose_name_plural': 'DeliveryService',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('source_id', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
            },
        ),
        migrations.CreateModel(
            name='DeliveryPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=250, null=True)),
                ('ref', models.CharField(blank=True, max_length=250, null=True)),
                ('name', models.CharField(max_length=250)),
                ('longitude', models.CharField(blank=True, max_length=250, null=True)),
                ('latitude', models.CharField(blank=True, max_length=250, null=True)),
                ('max_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('city_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='point_city', to='shipping.deliverycity')),
                ('service_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='point_service', to='shipping.deliveryservice')),
            ],
            options={
                'verbose_name': 'DeliveryPoint',
                'verbose_name_plural': 'DeliveryPoints',
            },
        ),
        migrations.AddField(
            model_name='deliverycity',
            name='service_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_service', to='shipping.deliveryservice'),
        ),
    ]
