# Generated by Django 3.1.7 on 2021-04-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='source_id',
        ),
        migrations.AddField(
            model_name='region',
            name='source',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
