# Generated by Django 3.2.8 on 2021-10-22 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0004_auto_20211022_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='novaposhtabranche',
            name='city_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shipping.novaposhtacity'),
        ),
        migrations.AddField(
            model_name='novaposhtacity',
            name='region_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shipping.novaposhtaregion'),
        ),
        migrations.AddField(
            model_name='novaposhtastreet',
            name='city_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shipping.novaposhtacity'),
        ),
        migrations.AlterField(
            model_name='novaposhtabranche',
            name='city',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='novaposhtacity',
            name='region',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='novaposhtastreet',
            name='city',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
