# Generated by Django 3.2.8 on 2021-10-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0005_auto_20211022_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novaposhtabranche',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
