# Generated by Django 3.2.9 on 2021-11-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0007_auto_20211126_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='novaposhtacity',
            name='settlement_type',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='novaposhtacity',
            name='settlement_type_description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='novaposhtacity',
            name='settlement_type_description_ru',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
