# Generated by Django 4.0 on 2021-12-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0008_auto_20211127_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='novaposhtacity',
            name='index1',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='novaposhtacity',
            name='index2',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='novaposhtacity',
            name='index_coatsu1',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='novaposhtacity',
            name='np_latitude',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='novaposhtacity',
            name='np_longitude',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='novaposhtacity',
            name='np_region',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='novaposhtacity',
            name='regions_description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='novaposhtacity',
            name='regions_description_ru',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
