# Generated by Django 3.1.7 on 2021-04-23 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=300, null=True)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('manufacturer_tecdoc_id', models.CharField(blank=True, max_length=300, null=True)),
                ('canbedisplayed', models.BooleanField(blank=True, default=0, null=True)),
                ('ispassengercar', models.BooleanField(blank=True, default=0, null=True)),
                ('iscommercialvehicle', models.BooleanField(blank=True, default=0, null=True)),
                ('ismotorbike', models.BooleanField(blank=True, default=0, null=True)),
                ('isengine', models.BooleanField(blank=True, default=0, null=True)),
                ('isaxle', models.BooleanField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': 'Manufacturer',
                'verbose_name_plural': 'Manufacturers',
            },
        ),
        migrations.CreateModel(
            name='ManufacturerModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=300, null=True)),
                ('source_manufacturer', models.CharField(blank=True, max_length=300, null=True)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('constructioninterval', models.CharField(blank=True, max_length=300, null=True)),
                ('model_tecdoc_id', models.CharField(blank=True, max_length=300, null=True)),
                ('manufacturer_tecdoc_id', models.CharField(blank=True, max_length=300, null=True)),
                ('canbedisplayed', models.BooleanField(blank=True, default=0, null=True)),
                ('ispassengercar', models.BooleanField(blank=True, default=0, null=True)),
                ('iscommercialvehicle', models.BooleanField(blank=True, default=0, null=True)),
                ('ismotorbike', models.BooleanField(blank=True, default=0, null=True)),
                ('isengine', models.BooleanField(blank=True, default=0, null=True)),
                ('isaxle', models.BooleanField(blank=True, default=0, null=True)),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tecdoc.manufacturer')),
            ],
            options={
                'verbose_name': 'Manufacturer',
                'verbose_name_plural': 'Manufacturers',
            },
        ),
    ]
