# Generated by Django 3.1.7 on 2021-04-23 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tecdoc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturermodels',
            options={'verbose_name': 'ManufacturerModel', 'verbose_name_plural': 'ManufacturerModels'},
        ),
    ]
