# Generated by Django 3.1.7 on 2021-04-23 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tecdoc', '0002_auto_20210423_1134'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ManufacturerModels',
            new_name='ManufacturerModel',
        ),
    ]
