# Generated by Django 3.2.3 on 2021-05-24 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecdoc', '0003_auto_20210423_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='country',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='manufacturermodel',
            name='commercial',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
    ]
