# Generated by Django 3.2.9 on 2021-11-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecdoc', '0004_auto_20210524_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='manufacturermodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
