# Generated by Django 3.2.5 on 2021-07-28 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_remove_manager_source_customer'),
        ('customers', '0002_auto_20210420_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpoint',
            name='customer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='point_customer', to='shop.customer'),
        ),
    ]
