# Generated by Django 3.2.5 on 2021-07-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customerpoint_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeragreement',
            name='is_status',
            field=models.BooleanField(default=1, null=True),
        ),
    ]
