# Generated by Django 3.2.9 on 2021-11-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customeragreement_is_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeragreement',
            name='finish_date',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
