# Generated by Django 3.2.9 on 2021-11-26 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_auto_20211126_1312'),
        ('customers', '0005_customeragreement_finish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpoint',
            name='latitude',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='customerpoint',
            name='longitude',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='balance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customeragreement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customercard',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customercontact',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customerdiscount',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customerpoint',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='CustomerPointGPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('source_id', models.CharField(blank=True, max_length=300, null=True)),
                ('add_name', models.CharField(blank=True, max_length=500, null=True)),
                ('customer', models.CharField(blank=True, max_length=500, null=True)),
                ('latitude', models.CharField(blank=True, max_length=500, null=True)),
                ('longitude', models.CharField(blank=True, max_length=500, null=True)),
                ('extra_name', models.CharField(blank=True, max_length=500, null=True)),
                ('area_ref', models.CharField(blank=True, max_length=300, null=True)),
                ('city_ref', models.CharField(blank=True, max_length=300, null=True)),
                ('street_type_ref', models.CharField(blank=True, max_length=300, null=True)),
                ('street_ref', models.CharField(blank=True, max_length=300, null=True)),
                ('customer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='point_gps_customer', to='shop.customer')),
            ],
            options={
                'verbose_name': 'CustomerPoint',
                'verbose_name_plural': 'CustomerPoints',
            },
        ),
    ]
