# Generated by Django 3.2.9 on 2021-11-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_auto_20211127_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpointgps',
            name='settlement_type',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='customerpointgps',
            name='settlement_type_description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='customerpointgps',
            name='street_type',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
