# Generated by Django 3.2.9 on 2021-11-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_auto_20211129_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpointgps',
            name='city',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='customerpointgps',
            name='oblast',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='customerpointgps',
            name='region_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='customerpointgps',
            name='street',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
