# Generated by Django 4.0 on 2021-12-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_auto_20211130_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeragreement',
            name='is_dropshipping',
            field=models.BooleanField(default=0, null=True),
        ),
    ]
