# Generated by Django 4.0 on 2021-12-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_customeragreement_is_dropshipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpointgps',
            name='index1',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='customerpointgps',
            name='index2',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='customerpointgps',
            name='index_coatsu1',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='customerpointgps',
            name='np_latitude',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='customerpointgps',
            name='np_longitude',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='customerpointgps',
            name='regions_description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
