# Generated by Django 3.1.7 on 2021-04-16 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0017_auto_20210416_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(default='Stock', max_length=300)),
                ('amount_total', models.IntegerField(default=0, null=True)),
                ('amount_account', models.IntegerField(default=0, null=True)),
                ('product', models.CharField(blank=True, max_length=300, null=True)),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_product', to='shop.product')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
            },
        ),
        migrations.CreateModel(
            name='ProductDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.CharField(blank=True, max_length=500, null=True)),
                ('value', models.CharField(blank=True, max_length=500, null=True)),
                ('product', models.CharField(blank=True, max_length=500, null=True)),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='description_product', to='shop.product')),
            ],
            options={
                'verbose_name': 'ProductDescription',
                'verbose_name_plural': 'ProductDescriptions',
            },
        ),
        migrations.CreateModel(
            name='ProductApplicability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.CharField(blank=True, max_length=250, null=True)),
                ('modification', models.CharField(blank=True, max_length=250, null=True)),
                ('engine', models.CharField(blank=True, max_length=250, null=True)),
                ('year', models.CharField(blank=True, max_length=250, null=True)),
                ('product', models.CharField(blank=True, max_length=500, null=True)),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicability_product', to='shop.product')),
            ],
            options={
                'verbose_name': 'ProductApplicability',
                'verbose_name_plural': 'ProductApplicabilitys',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True)),
                ('product', models.CharField(blank=True, max_length=300, null=True)),
                ('price_type', models.CharField(blank=True, max_length=300, null=True)),
                ('currency', models.CharField(blank=True, max_length=300, null=True)),
                ('currency_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_currency', to='shop.currency')),
                ('price_type_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_price_type', to='shop.pricetype')),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_product', to='shop.product')),
            ],
            options={
                'verbose_name': 'Price',
                'verbose_name_plural': 'Prices',
            },
        ),
        migrations.CreateModel(
            name='DeficitReserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_policy', models.CharField(blank=True, max_length=250, null=True)),
                ('amount', models.IntegerField(default=0, null=True)),
                ('product', models.CharField(blank=True, max_length=300, null=True)),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deficit_product', to='shop.product')),
            ],
            options={
                'verbose_name': 'DeficitReserve',
                'verbose_name_plural': 'DeficitReserves',
            },
        ),
        migrations.CreateModel(
            name='Cross',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_nr', models.CharField(blank=True, max_length=500, null=True)),
                ('search_nr', models.CharField(blank=True, max_length=500, null=True)),
                ('product', models.CharField(blank=True, max_length=500, null=True)),
                ('brand', models.CharField(blank=True, max_length=500, null=True)),
                ('brand_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cross_brand', to='shop.brand')),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cross_product', to='shop.product')),
            ],
            options={
                'verbose_name': 'Cross',
                'verbose_name_plural': 'Crosses',
            },
        ),
    ]
