# Generated by Django 3.2.3 on 2021-06-01 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20210511_1619'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductManufacturerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(blank=True, max_length=300, null=True)),
                ('manufacturer_name', models.CharField(blank=True, max_length=300, null=True)),
                ('model_name', models.CharField(blank=True, max_length=300, null=True)),
                ('manufacturer_tecdoc_id', models.CharField(blank=True, max_length=300, null=True)),
                ('model_tecdoc_id', models.CharField(blank=True, max_length=300, null=True)),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_product', to='shop.product')),
            ],
            options={
                'verbose_name': 'ProductManufacturerModel',
                'verbose_name_plural': 'ProductManufacturerModels',
            },
        ),
    ]
